### ISSUE TITLE
CHIP (last release from FT) is not working correctly

### ISSUE THREAD

**Issue by Archange427** [sosaria7/appleinpc#10]
Sorry but it seems I'm the one who always is announcing bad news ;)
With **CHIP**, the display is not synchronized and the music is played slowly.
The program use 2 timers from the Mockingboard in Slot#4 (=> Timer 1 from both 6522). 
Probably the cause of the issue (?!)

Information and download (DSK + src): http://fr3nch.t0uch.free.fr/CHP/CHP.html

**Comment by sosaria7** [comment]
I fixed that problem.
Please check version 0.1.46.1
Thank you.
