### ISSUE TITLE
Sather's "Little Text Window" doesn't render correctly

### ISSUE THREAD

**Issue by Archange427** [sosaria7/appleinpc#7]
Tom recently fixed a bug for AppleWin.
Seems that AIPC has the same issue.
Here a link to the discussion from AppleWin Github that brings more information and a link to download a .DSK for test:
https://github.com/AppleWin/AppleWin/issues/654

**Comment by sosaria7** [comment]
I fixed this issue.
You can download it here:
https://github.com/sosaria7/appleinpc/releases/tag/0.1.44.1
Thank you.

**Comment by Archange427** [comment]
As for the other issue, thanks for the quick fix!
