### ISSUE TITLE
6522 issue (timing to generate IRQ)

### ISSUE THREAD

**Issue by Archange427** [sosaria7/appleinpc#8]
Tom recently fixed another bug for AppleWin.
Seems that AIPC has the same issue.
Here a link to the discussion from AppleWin Github that brings more information about this issue:
https://github.com/AppleWin/AppleWin/issues/652

**Comment by sosaria7** [comment]
@Archange427  Thank you for reporting. 
I couldn't find TEST_INT_SYNC.zip at that issue.
Could you tell me where to download it?

**Comment by Archange427** [comment]
Oh yes Tom is talking about a .DSK that I had previously sent him and that had not been publicly released. Dunno how to attach a file here. I will send it directly to your email!

**Comment by Archange427** [comment]
@sosaria7: I just sent you by mail a fixed version including the interrupt delay minus 2 consistent with the behavior of a "real" 6522.
I hope it will help for your tests.

**Comment by sosaria7** [comment]
I fixed this issue.
You can download it here:
https://github.com/sosaria7/appleinpc/releases/tag/0.1.44.1
Thank you

**Comment by Archange427** [comment]
Thanks for this quick fix!
