### ISSUE TITLE
Page Select occuring 1 cycle delay

### ISSUE THREAD

**Issue by Archange427** [sosaria7/appleinpc#9]
Unlike the change of mode, it would seem that the page select does not take 1 additional cycle delay.
So the fix for issue #7 (https://github.com/sosaria7/appleinpc/issues/7) has introduced a new issue!

See the thread here for more details: https://github.com/AppleWin/AppleWin/issues/656 

Here are two test .DSK
[test_line_mode.zip](https://github.com/sosaria7/appleinpc/files/3341385/test_line_mode.zip)
[test_line_page.zip](https://github.com/sosaria7/appleinpc/files/3341386/test_line_page.zip)

The first uses a mode change ($C050/$C051) to display the line, 
The second uses a page change ($C055/$C054). 
Only the change of mode should display a shifted line (relative to the left edge)

Sorry for the confusion! 
The issue of delay for the page changing appeared only because the first problem (mode changing) had been corrected!

**Comment by sosaria7** [comment]
I fixed this issue.
And I tested some more cases.

- The memory read timing seems to be related to the instruction cycle.
   "lda ($02,x)" where x=0, ($02)=$c050, takes two more clocks for switching mode.
- There is no delay except TXTCLR, TXTSET, MIXEDCLR, MIXEDSET

Here is the disk image for test. (The test code is based on your program.)
[test.zip](https://github.com/sosaria7/appleinpc/files/3374047/test.zip)

the result on real Apple IIe.
![IMG_5444](https://user-images.githubusercontent.com/17441547/60908421-cab33300-a2b6-11e9-8a16-bedc1bb95a3b.JPG)

the result on AIPC
![aipc_sw_timing](https://user-images.githubusercontent.com/17441547/60908530-0cdc7480-a2b7-11e9-8f13-3745fd9f441d.png)

You can download the new version here.
https://github.com/sosaria7/appleinpc/releases/tag/0.1.45.1

Thank you.

**Comment by Archange427** [comment]
Very great job @sosaria7 (as usual)!
Does this mean that AIPC handles the timing of instructions exactly?
On a real 6502, LDA abs, read from effective address arises at cycle 4 (not at cycle 1).
But for LDA (zp,x), read from effective address arises at cycle 6.
-> That's why we got a +2 cycles delay (for line 6 compared to line 0).

Is the precise timing managed for all 6502 instructions with AIPC?

And thank you very much for the quick update and the very interesting tests that you did for the different switches!

**Comment by sosaria7** [comment]
No. managing exact timing for memory and cpu is difficult, and I think it is too inefficient for an emulator.
Instead, I resolved the problem by delaying a few more cycles for mode switching when indirect addressing.
For example, delaying cycle for IND is 1 cycle, for IND_X is 2 cycles, for IND_Y is 1 or 2 cycles.
All reading from memory is 3 cycles faster than a real machine, but it works similar :)
